config/routes.rb
AcrossAmerica::Application.routes.draw do
  resources :donations

  root :to => 'home#index'

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  attr_accessor :stripe_card_token, :amount
  
  def value
    value_in_pennies/100.0
  end
  
  def value=(val)
    value_in_pennies = val*100
  end
  
  def save_with_payment
    # binding.pry
    self.value_in_pennies = (amount.to_i * 100)
    if valid?
      charge = Stripe::Charge.create(amount: value_in_pennies, currency: "usd", card: stripe_card_token)
      self.stripe_charge = charge.id
      save!
    end
  rescue Stripe::InvalidRequestError => e
    logger.error "Stripe error while creating customer: #{e.message}"
    errors.add :base, "There was a problem with your credit card."
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @donations }
    end
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
    @donation = Donation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/new
  # GET /donations/new.json
  def new
    @donation = Donation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @donation }
    end
  end

  # GET /donations/1/edit
  def edit
    @donation = Donation.find(params[:id])
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(params[:donation])

    respond_to do |format|
      if @donation.save_with_payment
        format.html { redirect_to :root, success: 'Your donation was made successfully, thank you so much!' }
        format.json { render json: @donation, status: :created, location: @donation }
      else
        format.html { render action: "new" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /donations/1
  # PUT /donations/1.json
  def update
    @donation = Donation.find(params[:id])

    respond_to do |format|
      if @donation.update_attributes(params[:donation])
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy

    respond_to do |format|
      format.html { redirect_to donations_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @donated = Donation.sum(:value_in_pennies)/100
    @donation = Donation.new
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value_in_pennies %><br />
    <%= f.number_field :value_in_pennies %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<h1>Listing donations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Value in pennies</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @donations.each do |donation| %>
  <tr>
    <td><%= donation.name %></td>
    <td><%= donation.value_in_pennies %></td>
    <td><%= link_to 'Show', donation %></td>
    <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
    <td><%= link_to 'Destroy', donation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<h1>New donation</h1>

<%= render 'form' %>

<%= link_to 'Back', donations_path %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @donation.name %>
</p>

<p>
  <b>Value in pennies:</b>
  <%= @donation.value_in_pennies %>
</p>


<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>

app/views/home/index.html.erb
<div id="title">
  <h2>Send Will And Thomas</h2>
  <h1>Across America<span>.com</span></h1>
</div>
<%= content_tag(:div, nil, :id => 'donation_bar', :data => {donated: @donated, donated_formatted: number_to_currency(@donated, precision: 0)}) %>

<%= form_for @donation do |f| %>
  <%= f.hidden_field :stripe_card_token %>
  <%= f.label :email %>
  <%= f.text_field :email, placeholder:  "optional" %>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: "optional" %>
  <%= f.label :note %>
  <%= f.text_area :note, placeholder: "leave us a note if you want to", cols: 39, rows: 5 %>
  <%= f.label :amount %>
  <%= f.text_field :amount, placeholder: "in USD" %>
  <%= label_tag :card_number, "Credit Card Number" %>
  <%= text_field_tag :card_number, nil, name: nil %>
  <%= label_tag :card_code, "Security Code on Card (CVV)" %>
  <%= text_field_tag :card_code, nil, name: nil, placeholder: "the thingy on the back" %>
  <%= label_tag :card_month, "Card Expiration" %>
  <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"} %>
  <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year"} %>
  <br />
  <%= f.submit "Donate", class: "btn primary"%>
  <div id="stripe_error">
    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>
<% end %>

<div id="donate_now_tab">
  <span>Donate Now</span>
  <span style="display:none">Close</span>
</div>

<article id="what_we_are_doing">
  <header>What We're Doing</header>
  <p>Thomas and I are going across America to see the beautiful country we live in.  Along the way we'll be photographing, videoing, and just generally chronicling our journey, which you will be able to keep up with on this site!  There will be a live location tracker, blog posts, photos, and videos.  I'm sure they'll all be priceless.  But if you had to assign a price to it... you could donate that to our trip!  While we are primarily funding the trip ourselves, we aren't above a little help.  And if you do we've got some sweet prizes!</p>
  <p>We've calculated fuel costs, motel costs, and food costs and have come up with a goal amount of $5,000.  You're probably asking, "Hey! What do I get for sending you on this trip?".  Well I'm glad you asked!  There are some incentives, depending on how much you give.  Allow me to present to you, the chart:</p>
</article>

<article id="the_incentives">
  <header>The Incentives</header>
  <p>For any amount you donate, you will get all incentives at, and below your donation.</p>
  <dl>
    <dt>$5</dt>
      <dd>a post card</dd>
    <dt>$10</dt>
      <dd>We will dedicate a video to you</dd>
    <dt>$20</dt>
      <dd>Will will give you a hug</dd>
    <dt>$50</dd>
      <dd>we'll bring a photo of you on a stick with us and take pictures with it at places</dd>
    <dt>$100</dt>
      <dd>Thomas will give you a hug</dd>
  </dl>
</article>

<article id="the_route">
  <header>The Route</header>
  <p>The current plan is to head to New Mexico, then up to Colorado.  From there we'll go down to the Four Points, and then head over to San Fransisco.  Then up to Portland, Seattle, then over through Montana and North Dekota.  Then to Minneapolis, Chicago, St. Louis, Cincinnati, Detroit, Buffalo, Toronto, and Montreal.  From there we'll go through Maine, to the tip of Novascotia, back to Maine, Vermont, New Hampshire, Massachussetes, Rhode Island, Connecticut, Philidelphia, New Jersey, Delaware, DC, and on down the East Coast.  Then we'll go through Georga, Alabama, and Louisiana, and finally on back to Texas.</p>
  <p>We have not yet plotted it out on a map, but as soon as we do, you can be sure it will go right down there.  But until then, you can enjoy the route-less map of America.</p>
  <iframe width="960" height="540" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/?ie=UTF8&amp;ll=38.754083,-93.251953&amp;spn=37.434345,93.076172&amp;t=m&amp;z=4&amp;vpsrc=6&amp;output=embed"></iframe>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Us -> US</title>
  <script type="text/javascript" src="http://use.typekit.com/sdp0zzw.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= stylesheet_link_tag    "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <% unless flash.empty? %>
      <div id="success" class="alert-message success fade in" data-alert="alert">
        <a class="close" href="#">×</a>
        <p><%= flash[:success] %></p>
      </div>
    <% end%>
    <%= yield %>
  </div>
  <!--<div id="donate_flag">
    <%= image_tag("donate_flag.png") %>
  </div>-->
</body>
</html>